initial commit
PractiTest/pt-api-examples pull request #3
Opened 2017-11-06 11:30 UTC by vdemkiv

PractiTest Java Implementation for Steps

2017-11-12 12:27 UTC, stask requested changes
Can you please remove (and add to .gitignore) the `.idea` folder?

2017-11-12 12:41 UTC, stask requested changes

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/common/RequestFactory.java
> +package api.common;
Please move all files to `com.practitest` namespace. This one for example should be in `com.practitest.api.common` or maybe just `com.practitest.api` package.

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/PractiTestAPI.java
> +package api.practitest;
Since it's not a generic class like `RequestFactory`, let's move this class to `com.practitest.examples` package.

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/instance/Attributes.java
> +package api.practitest.instance;
This one can be in `com.practitest.api.model`.

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/instance/Data.java
> +package api.practitest.instance;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/instance/InstanceModel.java
> +package api.practitest.instance;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/runs/Attributes.java
> +package api.practitest.runs;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/runs/Data.java
> +package api.practitest.runs;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/runs/RunsModel.java
> +package api.practitest.runs;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/runs/StepModel.java
> +package api.practitest.runs;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/runs/Steps.java
> +package api.practitest.runs;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/sets/Attributes.java
> +package api.practitest.sets;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/sets/Data.java
> +package api.practitest.sets;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/sets/Instances.java
> +package api.practitest.sets;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/main/java/api/practitest/sets/SetsModel.java
> +package api.practitest.sets;
this too in `com.practitest.api.model`

2017-11-12 12:41 UTC, stask commented on PractiTest/src/test/java/RunWithTests.java
> +import api.practitest.PractiTestAPI;
Please move this file to `com.practitest.examples` package.

2017-11-13 21:54 UTC, vdemkiv commented
implemented changes as suggested

2017-11-15 15:54 UTC, stask requested changes
we almost there, just few more changes:

* remove .idea/uiDesigner.xml and .idea/workspace.xml
* the project 'pt-api-examples' contains examples for multiple languages and multiple api versions. We want to keep it like that for now. Which means that in order to merge this PR, we need to move these files a little bit. For example, the 'PractiTest/src' should become 'api.v2/java/src'; the 'PractiTest/pom.xml' should become 'api.v2/java/pom.xml', etc

The pom.xml will be a little trickier because you basically need to take the pom.xml that already exists in 'api.v2/java/' and add missing dependencies instead of replacing it.

2017-11-16 06:47 UTC, vdemkiv commented
I have moved my version to java.v2 folder to be able to store it separately.

2017-11-19 14:17 UTC, stask approved these changes

2017-11-23 15:19 UTC, merged